# This file builds given version of PHP and pushes it to Cachix cache.
# The following secrets need to be set:
# - “CACHIX_AUTH_TOKEN” for uploading built Nix packages to Cachix
name: Build

on:
  pull_request:
  push:

jobs:
  build:
    name: 'PHP ${{ matrix.php.major }}.${{ matrix.php.minor }}'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php:
          - major: 8
            minor: 1
          - major: 8
            minor: 0
          - major: 7
            minor: 4
          - major: 7
            minor: 3
          - major: 7
            minor: 2
          - major: 7
            minor: 1
          - major: 7
            minor: 0
          - major: 5
            minor: 6
      # We want to fix failures individually.
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v14

      - name: Set up Nix cache
        uses: cachix/cachix-action@v10
        with:
          name: fossar
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build PHP
        run: nix-build -A outputs.checks.x86_64-linux.php${{ matrix.php.major }}${{ matrix.php.minor }}-php

      - name: Build Imagick extension
        run: nix-build -A outputs.checks.x86_64-linux.php${{ matrix.php.major }}${{ matrix.php.minor }}-imagick

      - name: Build Redis extension
        run: nix-build -A outputs.checks.x86_64-linux.php${{ matrix.php.major }}${{ matrix.php.minor }}-redis

      - name: Build Redis 3 extension
        if: ${{ matrix.php.major < 8 }}
        run: nix-build -A outputs.checks.x86_64-linux.php${{ matrix.php.major }}${{ matrix.php.minor }}-redis3

      - name: Build MySQL extension
        if: ${{ matrix.php.major < 7 }}
        run: nix-build -A outputs.checks.x86_64-linux.php${{ matrix.php.major }}${{ matrix.php.minor }}-mysql

      - name: Build Xdebug extension
        run: nix-build -A outputs.checks.x86_64-linux.php${{ matrix.php.major }}${{ matrix.php.minor }}-xdebug

      - name: Build Tidy extension
        run: nix-build -A outputs.checks.x86_64-linux.php${{ matrix.php.major }}${{ matrix.php.minor }}-tidy

      - name: Check that composer PHAR works
        run: nix-build -A outputs.checks.x86_64-linux.php${{ matrix.php.major }}${{ matrix.php.minor }}-composer-phar

      - name: Validate php.extensions.mysqli default unix socket path
        run: nix-build -A outputs.checks.x86_64-linux.php${{ matrix.php.major }}${{ matrix.php.minor }}-mysqli-socket-path

      - name: Validate php.extensions.pdo_mysql default unix socket path
        run: nix-build -A outputs.checks.x86_64-linux.php${{ matrix.php.major }}${{ matrix.php.minor }}-pdo_mysql-socket-path
